#!/bin/bash

# If running on DES machines, use this conda env:
#conda activate /data/des80.a/data/imcmahon/micromamba/envs/mi38

# If running on a local machine, use these:
source ~/.bashrc
mamba activate mi38

export ROOT_DIR=$PWD
